bot:
  # client-token
  bot_token: 5916203690:AAE9AX2zGXy-lnJ6uKsgXYLGt4heqd1J3fs
  # client-channel-id
  channel_id: -1001901707923

db:
#  db_host: leeskbagenesh.beget.app
#  db_port: 3306
#  db_user: air_chan
#  db_pass: n88wjH2mVpl%
#  db_name: air_chan
  db_host: 192.168.197.128
  db_port: 3306
  db_user: root
  db_pass: "321"
  db_name: warehouse