bot:
  # client-token
  bot_token: "5916203690:AAE9AX2zGXy-lnJ6uKsgXYLGt4heqd1J3fs"
  # client-channel-id
  channel_id: -1001901707923
  # количество товаров в одном сообщении
  per_page: 5

es:
  es_host: "192.168.197.128"
  es_port: 9200
  es_user: "elastic"
  es_pass: "321"
  es_connections_limit: 50
  connection_attempt: 13
  products: "products-2024.01.27-000001"
  traders: "traders-2024.01.27-000001"
  consumers: "consumers-2024.01.27-000001"